package joro.nn.impl.core;

public enum TransferFunctionType {
  HARD_LIMIT,
  SYMMETRICAL_HARD_LIMIT,
  LINEAR,
  POSITIVE_LINEAR,
  SATURATING_LINEAR,
  SYMMETRIC_SATURATING_LINEAR,
  LOG_SIGMOID,
  HYPERBOLIC_TANGENT_SIGMOID,
  COMPETITIVE
}
